'use client';
import Link from 'next/link';
import { useState } from 'react';

export default function LoginPage(){
  const [message,setMessage]=useState('');
  function submit(e){e.preventDefault();setMessage('로그인 기능은 다음 단계에서 Supabase와 연결됩니다.');}
  return <main style={s.page}><section style={s.card}><Link href="/" style={s.brand}>케어택</Link><p style={s.kicker}>간병 전문 매칭 플랫폼</p><h1 style={s.title}>로그인</h1><p style={s.desc}>보호자와 간병인이 안전하게 서비스를 이용할 수 있도록 로그인하세요.</p><form onSubmit={submit} style={s.form}><label style={s.label}>이메일<input style={s.input} type="email" required placeholder="caretaek@example.com"/></label><label style={s.label}>비밀번호<input style={s.input} type="password" required placeholder="비밀번호를 입력하세요"/></label><button style={s.primary}>로그인</button></form><div style={s.social}><button style={{...s.socialBtn,background:'#fee500'}}>카카오로 로그인</button><button style={{...s.socialBtn,background:'#03c75a',color:'#fff'}}>네이버로 로그인</button></div>{message&&<p style={s.notice}>{message}</p>}<p style={s.bottom}>아직 회원이 아니신가요? <Link href="/signup" style={s.link}>회원가입</Link></p></section></main>
}
const s={page:{minHeight:'100vh',display:'grid',placeItems:'center',padding:'32px 16px',background:'linear-gradient(135deg,#eef6ff,#f9fbff)'},card:{width:'100%',maxWidth:460,background:'#fff',border:'1px solid #dce8f5',borderRadius:24,padding:32,boxShadow:'0 22px 60px rgba(20,70,120,.12)'},brand:{fontSize:28,fontWeight:900,color:'#0757a8',textDecoration:'none'},kicker:{margin:'4px 0 24px',fontSize:12,color:'#7890a6'},title:{fontSize:32,margin:'0 0 8px'},desc:{color:'#60758a',lineHeight:1.7,fontSize:14},form:{display:'grid',gap:16,marginTop:24},label:{display:'grid',gap:7,fontSize:13,fontWeight:700},input:{padding:'13px 14px',border:'1px solid #cad9e8',borderRadius:10,fontSize:14},primary:{border:0,borderRadius:10,padding:'14px 16px',background:'linear-gradient(135deg,#0d69dc,#0750ad)',color:'#fff',fontWeight:800,fontSize:15},social:{display:'grid',gap:10,marginTop:14},socialBtn:{border:0,borderRadius:10,padding:'13px 16px',fontWeight:800},notice:{background:'#eef6ff',color:'#0757a8',padding:12,borderRadius:10,fontSize:13},bottom:{textAlign:'center',fontSize:13,color:'#657b90',marginTop:22},link:{color:'#075dcc',fontWeight:800}}